name = "mercadopago-worker"
main = "src/index.ts"
compatibility_date = "2024-06-05"

[vars]
ORIGIN_ALLOWED = "https://fabiocolletto.github.io"
PLAN_STARTER_ID = "REPLACE_STARTER"
PLAN_PRO_ID     = "REPLACE_PRO"
PLAN_MASTER_ID  = "REPLACE_MASTER"
BACK_URL        = ""
ADMIN_PASSCODE  = "defina-um-passcode-forte"
