name: CI Zero (PR)
on:
  pull_request:
    branches: [Projeto-Marco]
concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI desativada nesta fase. Execução NOOP para manter status verde."
