name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect Node workspace
        id: workspace
        run: |
          if [ -f package.json ]; then
            echo "has_node=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_node=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
        if: steps.workspace.outputs.has_node == 'true'

      - name: Install dependencies
        run: npm install
        if: steps.workspace.outputs.has_node == 'true'

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps
        if: steps.workspace.outputs.has_node == 'true'

      - name: Testes end-to-end
        run: npm test
        if: steps.workspace.outputs.has_node == 'true'

      - name: Registrar verificação estática
        if: steps.workspace.outputs.has_node == 'false'
        run: echo "Nenhum workspace Node detectado; etapas baseadas em npm foram ignoradas."
