name: E2E smoke

on:
  pull_request:
    branches: [miniApp-base]
  push:
    branches: [miniApp-base]

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run smoke suite
        run: npm run test:e2e:smoke
