name: build

on:
  push:
    branches: [ "main" ]
    paths:
      - "abnt-conversor/**"
      - ".github/workflows/**"
  workflow_dispatch: {}   # permite rodar manualmente

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./abnt-conversor   # <- aponta para a pasta onde estão Dockerfile e app.py
          push: false
          tags: abnt-conversor:dev
