name: PR Guards
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Ensure CHANGELOG updated
        run: |
          base_sha="${{ github.event.pull_request.base.sha }}"
          head_sha="${{ github.event.pull_request.head.sha }}"
          if ! git diff --name-only "$base_sha" "$head_sha" | grep -q "^CHANGELOG.md$"; then
            echo "ERROR: CHANGELOG.md não foi atualizado neste PR."
            exit 1
          fi
