name: 5h — Publicar Assistente (Pages)
on:
  workflow_dispatch:
    inputs:
      slug:
        description: "assistentes/<slug> a publicar"
        required: true
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build artifact
        run: |
          mkdir -p _site/${{ github.event.inputs.slug }}
          cp -R assistentes/${{ github.event.inputs.slug }}/* _site/${{ github.event.inputs.slug }}/
      - uses: actions/upload-pages-artifact@v3
        with: { path: _site }
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
