name: 5h — Release
on:
  workflow_dispatch:
    inputs:
      version: { description: "Tag (ex: v3.0.1)", required: true }
      notes:   { description: "Notas do release", required: false }

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: |
          git tag -a "${{ github.event.inputs.version }}" -m "Release ${{ github.event.inputs.version }}"
          git push origin "${{ github.event.inputs.version }}"
      - name: Compose changelog (últimos 30 commits)
        id: cl
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.inputs.notes }}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          git log -n 30 --pretty=format:'- %s (%h)' >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name:     ${{ github.event.inputs.version }}
          body:     ${{ steps.cl.outputs.body }}
