name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Tipo de release"
        required: true
        type: choice
        options: [patch, minor, major]
  push:
    branches: [miniApp-base]
    tags-ignore: ['v*']

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: projeto-marco
          pull-request-title-pattern: 'chore(release): ${version}'
          changelog-types: |
            [{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"docs","section":"Documentation"},{"type":"chore","section":"Chores"},{"type":"ci","section":"CI"},{"type":"refactor","section":"Refactors"},{"type":"perf","section":"Performance"},{"type":"test","section":"Tests"}]
          include-v-in-tag: true
          extra-files: |
            docs/RELEASE_PROCESS.md
            CHANGELOG.md
