name: Criar Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag (ex: v3.0.0)"
        required: true
      notes:
        description: "Notas rápidas do release"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Criar tag
        run: |
          git tag -a "${{ github.event.inputs.version }}" -m "Release ${{ github.event.inputs.version }}"
          git push origin "${{ github.event.inputs.version }}"
      - name: Montar changelog simples
        id: cl
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "Versão: ${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "${{ github.event.inputs.notes }}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "Commits recentes:" >> $GITHUB_OUTPUT
          git log -n 20 --pretty=format:'- %s (%h)' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ steps.cl.outputs.changelog }}
